### ISSUE TITLE
I have one question about the FRAME_LEN and HOP 

### ISSUE THREAD

**Issue by ASR2020Guru** [cam-mobsys/covid19-sounds-neurips#2]
Hi team,

Thanks for your excellent work and share to the community.

I have one question about the FRAME_LEN and HOP

In your code:
```
SR = 16000  # sample rate
SR_VGG = 16000  # VGG pretrained model sample rate
FRAME_LEN = int(SR / 10)  # 100 ms
HOP = int(FRAME_LEN / 2)  # 50%overlap, 5ms
```
In this case, should the FRAME_LEN and HOP be 1600 and 800 instead of 100ms and 5ms ?

I am confused about this part.

Thanks

**Comment by andylamp** [comment]
hi, thanks for reaching out. The `SR` variable is sample rate and its unit of measurement is not time but rather Hertz. In this instance, we take 16000 samples per second. The frame length in this instance we want to be 100ms (out of 1000ms which comprises one second), hence we take 1/10th of the samples per second as per `FRAME_LEN` variable. A similar analogy holds for `HOP` variable as well. For more information perhaps you can check out `librosa` [glossary](https://librosa.org/doc/latest/glossary.html?highlight=frame%20length) that provides the required definitions for these terms.

Hope this helps.

**Comment by ASR2020Guru** [comment]
Thanks for your helpful information.
