### ISSUE TITLE
How can I get dataset？

### ISSUE THREAD

**Issue by 0nem0relight** [cam-mobsys/covid19-sounds-neurips#3]
How can I get dataset？

**Comment by andylamp** [comment]
Hi there @0nem0relight and thank you for your interest in this. To get the dataset you need to follow the procedure outlined in our website [here](https://www.covid-19-sounds.org/en/blog/neurips_dataset.html).

Thanks!

PS: please close the issue if you think we answered your question or I will close it after few days of inactivity!

**Comment by 0nem0relight** [comment]
Thank you！！！
